name: Cleanup

on:
  workflow_dispatch:

permissions:
  deployments: write

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Delete deployments
        uses: strumwolf/delete-deployment-environment@v3
        with:
          token: ${{ github.token }}
          environment: github-pages
